---
- name: Update Prometheus Configuration for Hardware Monitoring
  hosts: k3s_masters
  become: true
  
  tasks:
    - name: Create new Prometheus configuration
      copy:
        dest: /tmp/prometheus-config.yml
        content: |
          global:
            scrape_interval: 15s
            evaluation_interval: 15s
          
          rule_files:
            - "hardware-alerts.yml"
          
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']
            
            - job_name: 'proxmox-hardware'
              static_configs:
                - targets: ['192.168.2.100:9100']
              scrape_interval: 10s
              metrics_path: /metrics
              params:
                collect[]:
                  - hwmon
                  - thermal_zone
                  - cpu
                  - meminfo
                  - diskstats
                  - netdev
                  - filesystem
              relabel_configs:
                - source_labels: [__address__]
                  target_label: instance
                  replacement: 'proxmox-host'
            
            - job_name: 'kubernetes-nodes'
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - source_labels: [__address__]
                  regex: '(.*):10250'
                  target_label: __address__
                  replacement: '${1}:9100'
    
    - name: Copy hardware alerts to K3s master
      copy:
        src: "{{ playbook_dir }}/../../monitoring/prometheus-rules/hardware-alerts-enhanced.yml"
        dest: /tmp/hardware-alerts.yml
    
    - name: Update Prometheus ConfigMap
      shell: |
        kubectl create configmap prometheus-config-new \
          --from-file=prometheus.yml=/tmp/prometheus-config.yml \
          --from-file=hardware-alerts.yml=/tmp/hardware-alerts.yml \
          -n monitoring --dry-run=client -o yaml | kubectl apply -f -
        kubectl delete configmap prometheus-config -n monitoring --ignore-not-found
        kubectl patch configmap prometheus-config-new -n monitoring --type='merge' -p='{"metadata":{"name":"prometheus-config"}}'
        kubectl delete configmap prometheus-config-new -n monitoring
    
    - name: Restart Prometheus deployment
      shell: |
        kubectl rollout restart deployment/prometheus -n monitoring
        kubectl rollout status deployment/prometheus -n monitoring --timeout=300s
