apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: gitea
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/component: config
data:
  app.ini: |
    APP_NAME = Homelab Gitea
    RUN_MODE = prod
    RUN_USER = git
    
    [security]
    INSTALL_LOCK   = true
    SECRET_KEY     = {{ gitea_secret_key }}
    INTERNAL_TOKEN = {{ gitea_internal_token }}
    
    [database]
    DB_TYPE  = postgres
    HOST     = postgresql.postgresql.svc.cluster.local:5432
    NAME     = gitea
    USER     = gitea
    PASSWD   = {{ gitea_db_password }}
    SSL_MODE = disable
    CHARSET  = utf8
    
    [repository]
    ROOT = /data/git/repositories
    
    [server]
    PROTOCOL         = http
    DOMAIN           = gitea.local
    HTTP_PORT        = 3000
    ROOT_URL         = http://gitea.local:3000/
    DISABLE_SSH      = false
    SSH_PORT         = 22
    SSH_LISTEN_PORT  = 2222
    LFS_START_SERVER = true
    
    [mailer]
    ENABLED = false
    
    [service]
    REGISTER_EMAIL_CONFIRM            = false
    ENABLE_NOTIFY_MAIL                = false
    DISABLE_REGISTRATION              = false
    ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
    ENABLE_CAPTCHA                    = false
    REQUIRE_SIGNIN_VIEW               = false
    DEFAULT_KEEP_EMAIL_PRIVATE        = false
    DEFAULT_ALLOW_CREATE_ORGANIZATION = true
    DEFAULT_ENABLE_TIMETRACKING       = true
    NO_REPLY_ADDRESS                  = noreply.gitea.local
    
    [picture]
    DISABLE_GRAVATAR        = false
    ENABLE_FEDERATED_AVATAR = true
    
    [openid]
    ENABLE_OPENID_SIGNIN = true
    ENABLE_OPENID_SIGNUP = true
    
    [session]
    PROVIDER = file
    
    [log]
    MODE      = file
    LEVEL     = info
    ROOT_PATH = /data/gitea/log
    
    [markup.asciidoc]
    ENABLED = true
    FILE_EXTENSIONS = .adoc,.asciidoc
    RENDER_COMMAND = asciidoc --out-file=- -
    IS_INPUT_FILE = false