name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          # Optional: add configuration for the action
          fail-on-severity: moderate
          allow-licenses: BSD-3-Clause, MIT, Apache-2.0, ISC, GPL-3.0
          deny-licenses: GPL-2.0, LGPL-2.1